"""Entropy acquisition with provenance attestation."""

from .backends import (  # noqa: F401
    ANU_KEYED_URL,
    ANU_LEGACY_URL,
    ANU_MAX_ITEMS_PER_REQUEST,
    COMMITMENT_ALGORITHM,
    COMMITMENT_DOMAIN,
    DEFAULT_BACKEND,
    DEFAULT_ON_FAILURE,
    AnuQrngBackend,
    EntropyAttestation,
    EntropyBackend,
    EntropyResult,
    IbmQuantumBackend,
    OnFailure,
    QrngUnavailable,
    SystemEntropyBackend,
    UsbQrngBackend,
    commit,
    get_backend,
    get_entropy,
)
from .beacon import (  # noqa: F401
    BEACON_PULSE_BYTES,
    NIST_BEACON_BASE,
    BeaconPulse,
    NistBeaconBackend,
)
from .mixing import (  # noqa: F401
    KDF_NAME,
    MixedEntropyAttestation,
    MixedEntropyResult,
    NoSecretEntropy,
    SourceContribution,
    attest_explicit_seed,
    default_sources,
    hkdf,
    mix_entropy,
)

# Re-exports are the public surface of this subpackage. Naming them explicitly
# keeps `from qknot.signing.entropy import X` valid under a strict type checker,
# which treats an unlisted re-export as private.
__all__ = [
    "ANU_KEYED_URL",
    "ANU_LEGACY_URL",
    "ANU_MAX_ITEMS_PER_REQUEST",
    "BEACON_PULSE_BYTES",
    "COMMITMENT_ALGORITHM",
    "COMMITMENT_DOMAIN",
    "DEFAULT_BACKEND",
    "DEFAULT_ON_FAILURE",
    "KDF_NAME",
    "NIST_BEACON_BASE",
    "AnuQrngBackend",
    "BeaconPulse",
    "EntropyAttestation",
    "EntropyBackend",
    "EntropyResult",
    "IbmQuantumBackend",
    "MixedEntropyAttestation",
    "MixedEntropyResult",
    "NistBeaconBackend",
    "NoSecretEntropy",
    "OnFailure",
    "QrngUnavailable",
    "SourceContribution",
    "SystemEntropyBackend",
    "UsbQrngBackend",
    "attest_explicit_seed",
    "commit",
    "default_sources",
    "get_backend",
    "get_entropy",
    "hkdf",
    "mix_entropy",
]
